# https://docs.spring.io/spring-boot/appendix/application-properties/index.html#appendix.application-properties.data
spring:
  application:
    name: libraryapi
    output:
      ansi:
        enabled: ALWAYS

  #Conexão
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  #JPA
  jpa:
    show-sql: true
    hibernate:
      ddl_auto: update # none, create, create-drop, update
    properties:
      hibernate.format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

logging:
  file:
    name: app.log
  level:
    root: warn
    com:
      github:
        sergiocostaczr: trace
    org:
      springframework:
        web: debug
        security: trace

# listado por níveis
# trace - mais detalhado
# debug
# info
# warn
# error

management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: '*'


# desabilita as responses automaticas
springdoc:
  override-with-generic-response: false
